#!/bin/bash

. etc/shared_config

_BINDIR="bin"

_CSTANDART="c99"
_CFLAGS="-Wall -Wextra -O3 -std=${_CSTANDART} -flto -l:cimgui.so -lraylib -lm"

# vendor includes and libs
_CFLAGS="${_CFLAGS} -I${_VENDOR_DIR}/include"
_CFLAGS="${_CFLAGS} -L${_VENDOR_DIR}/lib -Wl,-R${_VENDOR_DIR}/lib"

# remove annoying warnings from raygui
_CFLAGS="${_CFLAGS} -Wno-unused-variable -Wno-unused-parameter"

_CFLAGS="${_CFLAGS} -DRAYGUI_IMPLEMENTATION"

_EDITOR_SOURCES="src/editor.c src/ui.c ${_VENDOR_DIR}/rlcimgui.c"
_MAPREADER_SOURCES="examples/readmap.c"

mkdir -p ${_BINDIR}

# prefer gcc over tcc UNLESS `-t` is provided
if [[ $1 = "-t" ]]; then
    tcc ${_EDITOR_SOURCES} ${_CFLAGS} -o ${_BINDIR}/editor
else
    _CFLAGS="${_CFLAGS} -Wl,--gc-sections -ffunction-sections -fdata-sections"
    gcc ${_EDITOR_SOURCES} ${_CFLAGS} -o ${_BINDIR}/editor
    gcc ${_MAPREADER_SOURCES} ${_CFLAGS} -Isrc -o ${_BINDIR}/mapreader
fi

strip -S -s -R .comment -R .gnu.version ${_BINDIR}/editor
strip -S -s -R .comment -R .gnu.version ${_BINDIR}/mapreader

cloc . --exclude-dir=${_VENDOR_DIR},bin,.vscode,tmp --exclude-lang='Bourne Again Shell',diff,INI

wc -c ${_BINDIR}/editor